Week 9 assignment
pesto-students/p3-shashank-sachin286 pull request #11
Opened 2022-08-22 12:44 UTC by sachin286

2022-08-22 15:08 UTC, ShashankSuresh requested changes

2022-08-22 15:08 UTC, ShashankSuresh commented on Week-9/todolist/src/App.js
> +    console.log(newTodos);
Please remove `console.log` statements

2022-08-22 15:08 UTC, ShashankSuresh commented on Week-9/todolist/src/App.js
> +  const [todos, setTodos] = React.useState([
`import React, { useState } `

The above is a better way of including hooks than `React.useState`

2022-08-22 15:08 UTC, ShashankSuresh commented on Week-9/todolist/src/App.js
> +function FormTodo({ addTodo }) {
This could be a separate component.

2022-08-22 15:08 UTC, ShashankSuresh commented on Week-9/todolist/src/App.js
> +function Todo({ todo, index, markTodo, removeTodo }) {
This could be a separate component.

2022-08-22 15:08 UTC, ShashankSuresh commented
@sachin286 Please attach screenshots of the app.

2022-08-22 15:12 UTC, ShashankSuresh commented
<img width="519" alt="image" src="https://user-images.githubusercontent.com/13508322/185955958-2c381dc1-5cef-441f-8526-1e5f29bb77c8.png">

Im able to add an empty todo item.

2022-08-22 15:14 UTC, ShashankSuresh commented
<img width="499" alt="image" src="https://user-images.githubusercontent.com/13508322/185956048-3ad3ab3e-b7ca-471d-a749-937f5d3637ae.png">
Please add a key value to all elements which are constructed using a loop.

2022-08-23 06:08 UTC, sachin286 commented
updated the codebase as suggested

2022-08-23 07:44 UTC, ShashankSuresh approved these changes

2022-08-23 09:10 UTC, merged