Excersie-1.2
pesto-students/p3-shashank-sachin286 pull request #2
Opened 2022-06-17 16:24 UTC by sachin286

week 1 exercise 1.2 html page design

2022-06-17 20:36 UTC, sachin286 commented
@ShashankSuresh 
I have added both the assignments into the same PR

2022-06-19 06:27 UTC, ShashankSuresh requested changes

2022-06-19 06:27 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/index.html
> +    * {
Kindly create a new css file for styles.

2022-06-19 06:27 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/index.html
> +    table {
please add parent classes for all children and grandchildren.

2022-06-19 06:27 UTC, ShashankSuresh commented on Week-1/Exercise-1.1/Readme.md
> +# How does a Browser work
Good research and analysis. Good job. 

Can we talk a bit more on how the DOM is created? (HTML + CSS DOM) ?

2022-06-21 18:53 UTC, sachin286 commented
changes have been added to the same

2022-06-22 14:40 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/index.html
> +<body style="border-right:3px solid black; border-top: 3px solid black;">
can we remove all the inline styles and move them to css classes?

2022-06-23 17:17 UTC, sachin286 commented
all the inline styles have been moved into the css file

2022-06-23 18:43 UTC, ShashankSuresh requested changes

2022-06-23 18:43 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/style.css
> +  background-color: white;
can we have this in css variables?

2022-06-23 18:43 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/style.css
> +  font-weight: bold;
can we have this in css variables?

2022-06-23 18:43 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/style.css
> +  background-color: rgb(60, 90, 146);
can we have this in css variables?

2022-06-23 18:43 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/style.css
> +  background-color: gainsboro;
can we have this in css variables and as hex colors?

2022-06-23 18:43 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/index.html
> +<html>
Looks good. Good job :)

2022-06-25 04:56 UTC, sachin286 commented
all css variables added and updated the file

2022-06-25 06:22 UTC, ShashankSuresh commented on Week-1/Exercise-1.2/style.css
> +:root {
Minor fix which can be done later. 

Rearrange based on variable type:

```
// Colors 
  --white: #ffffff;
  --black: #000000;
  --primary-blue: #1d0eed; // better naming convention
  --secondary-blue: #3c5a92; // better naming convention
  --gainsboro : #dcdcdc; // identify color using name

/* Font families. */
--font-family-sans: "Roboto", sans-serif;
--font-family-serif: "Playfair Display", serif;

/* Font sizes. */
--font-size-sm: 0.875rem;
--font-size-md: 1rem;
--font-size-lg: 1.125rem;
--font-size-xl: 1.25rem;
--font-size-2xl: 1.5rem;
--font-size-3xl: 2rem;
--font-size-4xl: 3rem;

/* Numeric keyword values */
font-weight: 100;
font-weight: 200;
font-weight: 300;
font-weight: 400;// normal
font-weight: 500;
font-weight: 600;
font-weight: 700;// bold
font-weight: 800;
font-weight: 900;
```

2022-06-25 06:23 UTC, ShashankSuresh approved these changes

2022-06-25 06:28 UTC, merged