Week 2 assignments
pesto-students/p3-shashank-sachin286 pull request #3
Opened 2022-06-25 10:16 UTC by sachin286

2022-06-27 09:21 UTC, ShashankSuresh requested changes

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/index.html
> +<html>
Please use a Prettifer plugin to intend the code.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +	margin:0px;
Same here for indentation.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +	font-family: Arial;
Please add this as variable

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +@media only screen and (max-width: 629px) {
Please add media queries to the end of the file

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  color: #fff;
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  font-size: 24px;
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  box-shadow: 0 5px #666;
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +.button:hover {background-color: #3e8e41}
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  background-color: #04AA6D;
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  box-shadow: 0 9px #999;
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  background-color: #3e8e41;
Move this to variables please.

2022-06-27 09:21 UTC, ShashankSuresh commented on Week-2/Exercise-2.1/style.css
> +:root {
Good work on the variables.

2022-06-27 10:12 UTC, sachin286 commented
I have updated the files on the variables and styling

2022-06-27 11:29 UTC, ShashankSuresh requested changes

2022-06-27 11:29 UTC, ShashankSuresh commented on Week-2/Exercise-2.2/style.css
> +  --text-fam: Arial;
This can be renamed to `--font-family`

2022-06-27 11:42 UTC, sachin286 commented
variables names updated

2022-06-30 11:55 UTC, ShashankSuresh commented
1. Adding meta tags.
2. Responsiveness for mobile, tablet and desktop devices. 
3. Formatting (minor)
4. Attach screen-shots

2022-06-30 11:59 UTC, ShashankSuresh commented on Week-2/Exercise-2.1/style.css
> +}
The rotation for Blue and Yellow is reversed. Kindly made the necessary modification.

2022-07-01 13:53 UTC, sachin286 commented
<img width="519" alt="Screenshot 2022-07-01 at 7 22 24 PM" src="https://user-images.githubusercontent.com/46752637/176908185-f73b8ba7-4f6c-4abf-a4c9-ef6cf21647d9.png">

updated the format and added the changes mentioned

2022-07-01 19:01 UTC, ShashankSuresh approved these changes

2022-07-01 19:04 UTC, merged