Week 3 assignment
pesto-students/p3-shashank-sachin286 pull request #4
Opened 2022-07-01 19:06 UTC by sachin286

2022-07-02 06:30 UTC, ShashankSuresh requested changes
'Week-3/Exercise-3.2/apply or call.js' - The name of this file could be like this 'call-bind-apply.js' or 'callBindApply.js'. Its good to avoid spaces in file names.

2022-07-02 06:31 UTC, ShashankSuresh requested changes
Instead of having 2 files for call bind and apply example, we can have just 1 file which as all the 3 implementation.

2022-07-02 06:32 UTC, ShashankSuresh requested changes
'Week-3/Exercise-3.3/Output.txt' - Just to maintain consistency we have all files in lower case?

2022-07-02 06:33 UTC, ShashankSuresh commented on Week-3/Exercise-3.4/demo.js
> +function createStack() {
Great job.. :)

2022-07-02 06:33 UTC, ShashankSuresh commented on Week-3/Exercise-3.1/memoise.js
> +function memoize(func) {
Great job.. :)

2022-07-02 06:34 UTC, ShashankSuresh requested changes
Kindly do the necessary changes.

2022-07-02 07:05 UTC, sachin286 commented
@ShashankSuresh changes have been implemented

2022-07-03 05:16 UTC, ShashankSuresh approved these changes
Great work. :)

2022-07-03 06:29 UTC, merged