week 4 assignment
pesto-students/p3-shashank-sachin286 pull request #5
Opened 2022-07-03 11:50 UTC by sachin286

2022-07-08 12:55 UTC, ShashankSuresh requested changes

2022-07-08 12:55 UTC, ShashankSuresh commented on Week-4/Exercise-4.2/inheritance.js
> +var Person = function () {};
The `var `keyword is considered dead in JS world. So lets use either `let `or `const`. In this scenario, lets use `const`.

2022-07-08 12:55 UTC, ShashankSuresh commented on Week-4/Exercise-4.2/inheritance.js
> +him.teach("Inheritance");
Per our discussion, kindly make the changes :)

2022-07-09 08:56 UTC, sachin286 commented
requested changes updated

2022-07-10 19:22 UTC, ShashankSuresh approved these changes
Looks good. Good work. :)

2022-07-10 19:45 UTC, merged